### ISSUE TITLE
React?

### ISSUE THREAD

**Issue by sammyjava** [jimmyrocks/maplibre-gl-vector-text-protocol#1]
Hi! I have a need to display KML placemarks on a map, but I'm in a React environment. I've tried to get this to run under React, but there's a fundamental issue, i think, with worker_threads. Do you think it's possible to run this under React and, if so, any tips? Thanks!

**Comment by jimmyrocks** [comment]
This is an interesting issue. I haven't tried this with React, but I do use React for some other projects. I know that Next.js will throw errors with Worker_threads, since it uses node.js, which doesn't support workers. I think the easiest fix for this issue would be to have the use of workers optional. I'll see if I can add an options and get back to you.

**Comment by jimmyrocks** [comment]
I added some code to check to make sure the web worker is available before trying to use it. Let me know if that works. This is probably something I should be doing anytime that I use a webworker, so thanks for finding this!

**Comment by sammyjava** [comment]
Will do, heading off to England in five minutes but I'll hit it when I get back in a week. ;) Much appreciated!

**Comment by jimmyrocks** [comment]
@sammyjava have you had a chance to look at this again?

**Comment by sammyjava** [comment]
Oh, shoot, no, sorry -- I ended up using react-leaflet-kml (and leaflet-fullscreen) which met my KML needs. Those install leaflet, leaflet-kml, and react-leaflet as dependencies.

But I'll give this a shot and report back, totally forgot about it!
