### ISSUE TITLE
how can i get geojson data from kml or gpx file?

### ISSUE THREAD

**Issue by anders86755** [jimmyrocks/maplibre-gl-vector-text-protocol#8]
how can i get geojson data from kml or gpx file?

My code:

   ```
 let data;
    if (fileType === 'kml') {
        data = "kml://" + fileURL;
    } else if (fileType === 'gpx') {
        data = "gpx://" + fileURL;
    } else if (fileType === 'geojson') {
        data = fileURL;
    }
    window.map.addSource(sourceId, {
        type: 'geojson',
        data: data
    });
```
I want to get the coordinates of all points from the data, but there is no suitable way.

I think it would be very useful if you could provide an interface that can export geojson objects.

for example: data.exportGeojson() 

Because sometimes in addition to displaying files on the map, we also want to do other processing on these geographical data.

By the way, your project is great and helped me a lot. Thanks a lot.

**Comment by jimmyrocks** [comment]
You should be able to do something like this with the project currently
`window.VectorTextProtocol.VectorTextProtocol({url: 'kml://https://loc8.us/maplibre-gl-vector-text-protocol/examples/data/cape_may_incorporated_places.kml'},(error,data) => console.log(data))`

Your code could be adapted like this:
```js
const vectorTextProtocol = window.VectorTextProtocol.VectorTextProtocol;
const processData = (url, fileType) => new Promise((res, rej) => {
    let [prefixedUrl];
    if (fileType === 'kml') {
        prefixedUrl = "kml://" + fileURL;
    } else if (fileType === 'gpx') {
        prefixedUrl = "gpx://" + fileURL;
    } else if (fileType === 'geojson') {
        prefixedUrl = fileURL;
    } else {
        rej('Format ' + fileTile + ' is not supported')
    }
    // You could also use: prefixedUrl = fileType + '://' + fileUrl;

    vectorTextProtocol({url: prefixedUrl}, (error, data) => {
        if (error) {
            rej(error);
        } else {
            res(data);
        }
    })
});

const fileType = 'kml';
const fileURL = 'https://loc8.us/maplibre-gl-vector-text-protocol/examples/data/cape_may_incorporated_places.kml'

processData(fileUrl, fileType)
    .then(data => {
        /* DO STUFF WITH GEOJSON DATA */
        window.map.addSource(sourceId, {
            type: 'geojson',
            data: data
        });
    })
    .catch(error => console.error(error))
```

Really, there's no reason _not_ to expose the [`processData`](https://github.com/jimmyrocks/maplibre-gl-vector-text-protocol/blob/60584351973eaf16036d49d76939e4dffe39709a/src/index.ts#L39) function, which works exactly as the processData function defined in the example. So, I'll look into that.

Once that change is in, you can just use `VectorTextProtocol.processData` instead of creating the `processData` function yourself.

**Comment by jimmyrocks** [comment]
I updated it to export the [processData](https://github.com/jimmyrocks/maplibre-gl-vector-text-protocol/blob/60584351973eaf16036d49d76939e4dffe39709a/src/index.ts#L39) function with this commit: https://github.com/jimmyrocks/maplibre-gl-vector-text-protocol/commit/b5f6bfca143e75e7565a19d7e7dc75cc30cca8d9

It should be as simple as this now:
```js
const fileType = 'kml';
const fileURL = 'https://loc8.us/maplibre-gl-vector-text-protocol/examples/data/cape_may_incorporated_places.kml'

VectorTextProtocol.processData(fileUrl, fileType)
    .then(data => {
        /* DO STUFF WITH GEOJSON DATA */
        window.map.addSource(sourceId, {
            type: 'geojson',
            data: data
        });
    })
    .catch(error => console.error(error))
```
